# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='colegiado',
            field=models.CharField(default='oi', max_length=200),
            preserve_default=False,
        ),
    ]
