# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_docente_colegiado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Comissao',
        ),
    ]
