# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso_extensao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoRelatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('frequencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRelatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoCertificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('publico_atingido', models.IntegerField()),
                ('resumo', models.CharField(max_length=200)),
                ('atividades_realizadas_programacao', models.CharField(max_length=200)),
                ('dificuldades', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.EstadoRelatorio')),
                ('projeto_extensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso_extensao.CursoExtensao')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.Relatorio')),
            ],
        ),
        migrations.AddField(
            model_name='certificadorelatorio',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.FuncaoCertificado'),
        ),
        migrations.AddField(
            model_name='certificadorelatorio',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.Relatorio'),
        ),
    ]
