# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
