# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_auto_20170704_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
