# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_relatorio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRelatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='relatorio.EstadoRelatorio'),
            preserve_default=False,
        ),
    ]
