# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0006_relatoriofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofile',
            name='nome',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
