# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0003_auto_20170803_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comissao_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comissao.Comissao')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.Docente')),
            ],
        ),
        migrations.AddField(
            model_name='comissao',
            name='membros',
            field=models.ManyToManyField(related_name='membros', through='comissao.Comissao_Docente', to='docente.Docente'),
        ),
    ]
