# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsaoorcamentaria_cursoextensao',
            old_name='material_de_consumo',
            new_name='material_consumo',
        ),
        migrations.RemoveField(
            model_name='cursoextensao',
            name='periodo_de_realizacao',
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='periodo_realizacao_fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='periodo_realizacao_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
