# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor_cursoextensao',
            name='plano_trabalho',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
