# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteuniversitario_cursoextensao',
            name='colegiado',
        ),
    ]
