# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0002_remove_agenteuniversitario_cursoextensao_colegiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteuniversitario_cursoextensao',
            name='colegiado',
            field=models.CharField(default='oi', max_length=200),
            preserve_default=False,
        ),
    ]
