# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170702_1302'),
        ('curso_extensao', '0002_servidor_cursoextensao_plano_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoextensao',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.EstadosProjeto'),
            preserve_default=False,
        ),
    ]
