# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0002_auto_20170608_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextensao',
            name='periodo_realizacao_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cursoextensao',
            name='periodo_realizacao_inicio',
            field=models.DateField(),
        ),
    ]
