# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso_extensao', '0003_auto_20170609_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsaoorcamentaria_cursoextensao',
            name='curso_extensao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso_extensao.CursoExtensao'),
        ),
    ]
