# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170714_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Comissao',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
