# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_servidor_plano_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='servidor',
            name='colegiado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
