# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_auto_20170703_1413'),
        ('curso_extensao', '0003_cursoextensao_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('estado_parecer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EstadoProjeto')),
                ('projeto_extensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso_extensao.CursoExtensao')),
            ],
        ),
    ]
