# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parecer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parecer',
            old_name='comentario',
            new_name='numero_ata',
        ),
    ]
